import React, { useState } from 'react';
import { Sparkles, CheckCircle2, AlertTriangle, ArrowRight, Search } from 'lucide-react';
import { CleansedTransaction, SystemParameters } from '../types';
import { formatCurrency } from '../utils/engine';
import { InsightBlock } from './InsightBlock';
import { StatusBadge } from './StatusBadge';

interface CostCleansingViewProps {
  cleansed: CleansedTransaction[];
  parameters: SystemParameters;
  onNavigate: (tab: any) => void;
}

export const CostCleansingView: React.FC<CostCleansingViewProps> = ({
  cleansed,
  parameters,
  onNavigate,
}) => {
  const [filter, setFilter] = useState<'all' | 'Matched' | 'Unmatched'>('all');
  const [search, setSearch] = useState('');

  const currency = parameters.currencySymbol;

  const filtered = cleansed.filter((item) => {
    if (filter !== 'all' && item.status !== filter) return false;
    const q = search.toLowerCase();
    return (
      item.seq.toLowerCase().includes(q) ||
      item.payee.toLowerCase().includes(q) ||
      item.description.toLowerCase().includes(q) ||
      item.matchedCategory.toLowerCase().includes(q) ||
      item.matchedSubcategory.toLowerCase().includes(q)
    );
  });

  const matchedCount = cleansed.filter((c) => c.status === 'Matched').length;
  const unmatchedCount = cleansed.filter((c) => c.status === 'Unmatched').length;

  return (
    <div className="space-y-6 animate-fade-up">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-baseline sm:justify-between gap-2">
        <div>
          <div className="text-[11px] font-semibold text-[#888888] uppercase tracking-wider">
            Sheet Code: ENG_CostCleansing
          </div>
          <h1 className="font-display font-semibold text-[28px] tracking-display text-[#051C2C] leading-tight">
            Automated Cost Cleansing & Attribution Engine
          </h1>
          <p className="text-[13px] text-[#888888] mt-0.5">
            Formula-driven data pipeline standardizing dates, extracting periods, and classifying expenses.
          </p>
        </div>

        {/* Engine Match Stats */}
        <div className="flex items-center gap-2">
          <div className="bg-white px-3 py-1.5 rounded-[8px] border border-[#E8E8E6] text-right">
            <span className="text-[10px] text-[#888888] uppercase tracking-wider block">
              Classification Ratio
            </span>
            <span className="font-bold text-[#051C2C] text-[14px]">
              {matchedCount} / {cleansed.length} (
              {cleansed.length > 0 ? ((matchedCount / cleansed.length) * 100).toFixed(0) : 0}%)
            </span>
          </div>
        </div>
      </div>

      <InsightBlock
        title="Formula-Managed Immutable Output Layer"
        actionText={unmatchedCount > 0 ? 'Maintain Mapping Rules' : undefined}
        onAction={() => onNavigate('DIM_CostMapping')}
      >
        All cells below are dynamically generated by JavaScript array functions mirroring Excel 365{' '}
        <code>LET + FILTER + XLOOKUP + BYROW</code> formulas. If any row indicates{' '}
        <span className="text-[#D32F2F] font-semibold">⚠️ Unmatched</span>, adding its vendor
        keyword into <code>DIM_CostMapping</code> resolves the classification in real time without
        modifying the source ledger.
      </InsightBlock>

      {/* Filter and Search Bar - Clean Minimalism Card */}
      <div className="card">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-3 border-b border-[#E8E8E6] gap-3">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-[#2251FF]" />
            <h2 className="font-display font-semibold text-[18px] tracking-heading text-[#051C2C]">
              Cleansed Audit Records ({filtered.length} Displayed)
            </h2>
          </div>

          <div className="flex items-center gap-3">
            {/* Status Segmented control */}
            <div className="flex items-center bg-[#F5F5F2] p-0.5 rounded-[6px] text-[11px] font-medium">
              <button
                onClick={() => setFilter('all')}
                className={`px-3 py-1 rounded-[4px] cursor-pointer transition-colors ${
                  filter === 'all' ? 'bg-white shadow-xs text-[#051C2C] font-semibold' : 'text-[#888888]'
                }`}
              >
                All ({cleansed.length})
              </button>
              <button
                onClick={() => setFilter('Matched')}
                className={`px-3 py-1 rounded-[4px] cursor-pointer transition-colors ${
                  filter === 'Matched' ? 'bg-white shadow-xs text-[#051C2C] font-semibold' : 'text-[#888888]'
                }`}
              >
                Matched ({matchedCount})
              </button>
              <button
                onClick={() => setFilter('Unmatched')}
                className={`px-3 py-1 rounded-[4px] cursor-pointer transition-colors ${
                  filter === 'Unmatched' ? 'bg-white shadow-xs text-[#D32F2F] font-semibold' : 'text-[#888888]'
                }`}
              >
                Unmatched ({unmatchedCount})
              </button>
            </div>

            {/* Search */}
            <div className="relative w-44 sm:w-56">
              <Search className="w-3.5 h-3.5 text-gray-400 absolute left-2.5 top-2" />
              <input
                type="text"
                placeholder="Search cleansed items..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full pl-8 pr-2.5 py-1 text-[12px] rounded-[6px] border border-[#E8E8E6] focus:outline-none focus:border-[#2251FF]"
              />
            </div>
          </div>
        </div>

        <div className="overflow-x-auto mt-4">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr>
                <th className="table-th p-2.5 w-24 rounded-l-[6px]">Audit ID</th>
                <th className="table-th p-2.5 w-28">Std Date</th>
                <th className="table-th p-2.5 w-16 text-center">Period</th>
                <th className="table-th p-2.5 w-44">Payee</th>
                <th className="table-th p-2.5">Cleansed Description</th>
                <th className="table-th p-2.5 text-right w-28">Amount ({currency})</th>
                <th className="table-th p-2.5 w-40">Matched Category</th>
                <th className="table-th p-2.5 w-44">Matched Subcategory</th>
                <th className="table-th p-2.5 w-20 text-center">Method</th>
                <th className="table-th p-2.5 text-center w-28 rounded-r-[6px]">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#E8E8E6] text-[12px]">
              {filtered.map((item) => {
                const isUnmatched = item.status === 'Unmatched';
                const isNegative = item.amount < 0;

                return (
                  <tr
                    key={item.id}
                    className={`hover:bg-[#F5F5F2] transition-colors ${
                      isUnmatched ? 'anomaly-row' : ''
                    }`}
                  >
                    <td className="p-2.5 font-mono text-[11px] font-semibold text-[#051C2C]">
                      {item.seq}
                    </td>
                    <td className="p-2.5 font-mono text-gray-600">{item.stdDate}</td>
                    <td className="p-2.5 text-center font-mono text-gray-500 text-[11px]">
                      {item.year}-M{String(item.month).padStart(2, '0')}
                    </td>
                    <td className="p-2.5 font-medium text-[#051C2C] truncate max-w-[150px]">
                      {item.payee}
                    </td>
                    <td className="p-2.5 text-gray-700 truncate max-w-[220px]" title={item.description}>
                      {item.description}
                    </td>
                    <td className="p-2.5 text-right font-mono font-semibold tabular-nums">
                      <span className={isNegative ? 'text-[#D32F2F]' : 'text-[#051C2C]'}>
                        {formatCurrency(item.amount, currency, 2)}
                      </span>
                    </td>
                    <td className="p-2.5">
                      <span
                        className={`text-[11px] font-medium ${
                          isUnmatched ? 'text-[#D32F2F]' : 'text-[#051C2C]'
                        }`}
                      >
                        {item.matchedCategory}
                      </span>
                    </td>
                    <td className="p-2.5 text-gray-600 truncate max-w-[160px]">
                      {item.matchedSubcategory}
                    </td>
                    <td className="p-2.5 text-center">
                      <span className="font-mono text-[11px] bg-gray-100 px-1.5 py-0.5 rounded text-gray-700">
                        {item.method}
                      </span>
                    </td>
                    <td className="p-2.5 text-center">
                      <StatusBadge
                        label={item.status === 'Matched' ? 'Matched' : 'Unmapped'}
                        variant={item.status === 'Matched' ? 'neutral' : 'negative'}
                      />
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
